### ISSUE TITLE
邮件提醒功能将独立出一个新的仓库

### ISSUE THREAD

**Issue by ConanYu** [ConanYu/GoodGuy#7]
原本是因为爬虫代码也写在本项目中，于是为了更好地开发而选择将邮件提供功能也写在了本仓库中。
如今爬虫代码已经迁移了，并使用gRPC进行调用，所以将会把邮件提醒功能独立开来，这样一个项目只做一件事情，后续的维护会更加轻松。

**Comment by 9lie** [comment]
什么时候弄

**Comment by ConanYu** [comment]
经评估无必要
